
export const CRYPTO_SLANG = [
  "WE ARE ACTUALLY SENDIN DIS!",
  "SENDING TO 100M MCAP...",
  "LFG!!! DIS IS GOING UP!",
  "NO JEETS ALLOWED ON THIS RIDE.",
  "WASD: WE ALWAYS SEND DIS.",
  "GREEN PILL ACTIVATED.",
  "PARABOLIC ARC DETECTED.",
  "SQUEEZE THE JEETS!",
  "DIS IS THE BIG ONE.",
  "WE SENDIN DIS TO VALHALLA.",
  "MOON MISSION AUTHORIZED.",
  "BULLISH MOMENTUM OVERFLOW.",
  "GENERATIONAL WEALTH DISPATCHED.",
  "WASD GANG STAND UP!",
  "PUMP IT TO THE CLOUDS.",
  "DIS IS LITERALLY SENDING.",
  "NO REVERSE, ONLY FORWARD.",
  "WAKE UP, WE SENDIN DIS.",
  "CHART LOOKS ABSOLUTELY JUICY."
];

export const CONTRACT_ADDRESS = "EAWhwEAu9qcp6wzDVMQzdQ5wcpivWXYUhBDv7huBpump";
export const TICKER = "$WASD";
export const FULL_NAME = "We Are Sendin Dis";
export const MAIN_IMG_URL = "https://pbs.twimg.com/media/G8k_4CAWEAAh-Jy?format=png&name=small";
