
export const CRYPTO_SLANG = [
  "RUGGED AGAIN? SADGE.",
  "DEV SOLD AT 10K MCAP.",
  "WEN MOON???",
  "NGMI IF YOU SELL NOW.",
  "LFG!!! TO THE MOON!",
  "SYSTEM ERROR: LIQUIDITY NOT FOUND.",
  "YOUR WALLET IS SUFFERING FROM PAPER HANDS.",
  "JEETS DETECTED IN THE VICINITY.",
  "DIAMOND HANDS REQUIRED TO CONTINUE.",
  "ERROR 404: LAMBO NOT FOUND.",
  "HODL FOR YOUR LIFE.",
  "BOUGHT THE TOP AGAIN, HUH?",
  "GENERATIONAL WEALTH LOADING...",
  "PEPE IS WATCHING YOU.",
  "JUST ONE MORE SHITCOIN...",
  "HTML IS THE FUTURE OF FINANCE.",
  "PUMP IT LOUDER!",
  "SER, PLS DO NOT REDEEM.",
  "FREN, ARE WE WINNING?"
];

export const CONTRACT_ADDRESS = "EhR8t2Hd9KikSPiRHdHs8WidCLa3T1VEPFpnCsRRpump";
export const TICKER = "$HTML";
export const FULL_NAME = "hope this moons later";
export const MAIN_IMG_URL = "https://wkkeyyrknmnynlcefugq.supabase.co/storage/v1/object/public/html/logo%20-%202025-12-18T203427.004.png";
